# Site settings
title: esm_206_244
email: ahorst@ucsb.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: allison_horst
github_username: allisonhorst

# Build settings
markdown: kramdown
encoding: UTF-8
